// Typed accessor for the gallery data generated by scripts/generate-gallery.mjs.
// The JSON is produced at build time (predev / prebuild); see AGENTS.md.
import galleryJson from "./gallery.json";

export interface GalleryImage {
  full: string;
  thumb: string;
  width: number;
  height: number;
  alt: string;
}

export interface GalleryProject {
  slug: string;
  title: string;
  images: GalleryImage[];
}

export interface GalleryCategory {
  slug: string;
  title: string;
  projects: GalleryProject[];
  images: GalleryImage[];
}

export interface GalleryData {
  generatedAt: string;
  categories: GalleryCategory[];
}

// Image paths are public-root-relative WITHOUT a leading slash — prepend
// `import.meta.env.BASE_URL` at render time (see HeroAnimation.astro pattern).
export const gallery: GalleryData = galleryJson as GalleryData;
